dubbo:
  application:
    name: dubbo-springboot-demo-consumer
  protocol:
    name: dubbo
    port: 20800
  registry:
    id: tts-zk-registry
    address: zookeeper://101.43.163.223:2181
  consumer:
    check: false
    timeout: 10000