dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: zk-registry
    address: zookeeper://101.43.163.223:2181
  config-center:
    address: zookeeper://101.43.163.223:2181
  metadata-report:
    address: zookeeper://101.43.163.223:2181
